include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/generated/*
  errors:
    todo: ignore
linter:
  rules:
    sort_constructors_first: true
    sort_pub_dependencies: true
    avoid_dynamic_calls: true
    avoid_relative_lib_imports: true
    no_duplicate_case_values: true
    no_self_assignments: true
    always_declare_return_types: true
    avoid_print: true
    use_build_context_synchronously: false
