name: tonic_synth_flutter
description: "Flutter App with Tonic audio synthesis library"
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.11.1

dependencies:
  code_assets: ^1.2.1
  cupertino_icons: ^1.0.8
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  flutter_soloud: ^4.0.9
  hooks: ^2.0.2
  logger: ^2.7.0
  path_provider: ^2.1.6
  share_plus: ^13.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true